import Foundation
import SwiftData

/// Coach v2 prescribed workout. Generated by CoachService.prescribeTodaysWorkout.
/// User can accept (becomes the actual session start), modify (edit inline), or
/// skip (status=skipped). Once a session is created from this prescription,
/// `sessionUUID` is set and status flips to `accepted`.
@Model
final class PrescribedWorkout {
    var generatedAt: Date = Date.distantPast
    var forDate: Date = Date.distantPast              // midnight in user's TZ for the day this prescription targets
    var workoutTypeRaw: String = PrescribedWorkoutType.rest.rawValue
    var template: String = "{}"                       // JSON-encoded sets/reps/exercises (lifts) or zones (basketball/swim)
    var rationale: String = ""                        // why this workout today, in user's voice
    var creativeTitle: String = ""                    // 2-4 word evocative name (e.g. "Quadzilla", "Sanity Session"). Empty for legacy rows; UI falls back to workoutType.displayName.
    var statusRaw: String = PrescribedWorkoutStatus.suggested.rawValue
    var sessionUUIDString: String?                    // FK to actual session if accepted (UUID encoded as string)
    var tokenUsage: Int = 0
    var modelUsed: String = "claude-sonnet-4-6"

    var workoutType: PrescribedWorkoutType {
        PrescribedWorkoutType(rawValue: workoutTypeRaw) ?? .rest
    }

    var status: PrescribedWorkoutStatus {
        get { PrescribedWorkoutStatus(rawValue: statusRaw) ?? .suggested }
        set { statusRaw = newValue.rawValue }
    }

    var sessionUUID: UUID? {
        get { sessionUUIDString.flatMap(UUID.init(uuidString:)) }
        set { sessionUUIDString = newValue?.uuidString }
    }

    init(generatedAt: Date,
         forDate: Date,
         workoutType: PrescribedWorkoutType,
         template: String = "{}",
         rationale: String = "",
         tokenUsage: Int = 0,
         modelUsed: String = "claude-sonnet-4-6") {
        self.generatedAt = generatedAt
        self.forDate = forDate
        self.workoutTypeRaw = workoutType.rawValue
        self.template = template
        self.rationale = rationale
        self.tokenUsage = tokenUsage
        self.modelUsed = modelUsed
    }
}

enum PrescribedWorkoutType: String, Codable, CaseIterable, Sendable {
    case liftA = "lift_a"
    case liftB = "lift_b"
    case basketball
    case swim
    case rest
    case custom

    var displayName: String {
        switch self {
        case .liftA:      return "Lift A"
        // lift_b stays the coach-facing key; the user-facing name follows
        // the Training hub's custom workout slot.
        case .liftB:      return "My Workout"
        case .basketball: return "Basketball"
        case .swim:       return "Swim"
        case .rest:       return "Rest"
        case .custom:     return "Custom"
        }
    }
}

enum PrescribedWorkoutStatus: String, Codable, CaseIterable, Sendable {
    case suggested
    case accepted
    case modified
    case skipped
    case completed
}
